services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/qbitorrent/config:/config
      - /media/vinicius/arquivos/dutraflix/qbitorrent/Downloads:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/radarr:/movies
      - /media/vinicius/arquivos/dutraflix/sonarr:/tv
      - /media/vinicius/arquivos/dutraflix/bazarr/config:/config
    ports:
      - '6767:6767'

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/prowlarr/config:/config
    ports:
      - '9696:9696'

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/radarr/config:/config
      - /media/vinicius/arquivos/dutraflix/qbitorrent/Downloads:/downloads
      - /media/vinicius/arquivos/dutraflix/radarr/movies:/movies
      - /media/vinicius/arquivos/dutraflix/radarr/anime:/anime
    ports:
      - '7878:7878'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/sonarr-config/:/config
      - /media/vinicius/arquivos/dutraflix/sonarr:/tv
      - /media/vinicius/arquivos/dutraflix/qbitorrent/Downloads:/downloads
    ports:
      - '8989:8989'
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/vinicius/arquivos/dutraflix/sonarr:/tv
      - /media/vinicius/arquivos/dutraflix/radarr/movies:/movies
      - /media/vinicius/arquivos/dutraflix/radarr/anime:/anime
      - /media/vinicius/arquivos/dutraflix/jellyfin/config:/config
      - /media/vinicius/arquivos/dutraflix/jellyfin/transcode:/transcode
    ports:
      - '8096:8096'
      - '8920:8920'
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    depends_on:
        - qbittorrent
        - sonarr
        - jellyfin
        - radarr
    environment:
        - LOG_LEVEL=debug
        - TZ=America/Sao_Paulo
    ports:
        - 5055:5055
    volumes:
        - /media/vinicius/arquivos/dutraflix/jellyseerr/config:/app/config
    restart: unless-stopped
